version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: frontend
    # المجلد يركب للـ hot-reload… لكن نحتاج node_modules داخل الحاوية
    volumes:
      - ./frontend:/app          # الكود
      - /app/node_modules        # تبعيات تبقى داخل الحاوية
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"


volumes:
  mysql_data:
